# Generated by Django 5.1 on 2025-01-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="registration_date",
            field=models.DateField(auto_now=True),
        ),
    ]
