# Generated by Django 5.1 on 2025-01-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_alter_eventregistration_registration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="registration_date",
            field=models.DateField(auto_created=True),
        ),
    ]
