# Generated by Django 5.1 on 2025-01-08 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0005_alter_eventregistration_registration_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventregistration",
            name="registration_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
